name: Generate Executable

on:
  workflow_dispatch:
    branches: [main]

  push:
    branches: [main]
    paths: [src/*, api/*]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: "3.12"
          spec: "src/gui.spec"
          requirements: "src/requirements.txt"
          upload_exe_with_name: "Pulsar Search"
